### ISSUE TITLE
Representing DPI-C imported functions

### ISSUE THREAD

**Issue by rachitnigam** [vegaluisjose/vast#3]
Following up on a slack conversation, we want to represent the following in our compiler backend:
```
import "DPI-C" function string futil_getenv (input string env_var);
string DATA;
initial begin
  DATA = futil_getenv("DATA");
  $display("DATA: %s", DATA);
  $readmemh({DATA, "/<mem_name>.out"}, <mem_name>.mem);
  ...
end
final begin
  $writememh({DATA, "/<mem_name>.out"}, <mem_name>.mem);
end
```
@vegaluisjose mentioned that he has an idea on how to represent the first `import` statement. For now, we're using the `Stmt::RawStr` representation.

**Comment by vegaluisjose** [comment]
Fixed [here](https://github.com/vegaluisjose/vast/commit/f24c7f7fcd7eb6862080c830c9f9e6b608d4744d)
